travis:
  secure:
    BINSTAR_TOKEN: bQHNX0GtP+o+uuum7Wxi5my6RMlcn2CSCgL0zer/eyY3nJ4WXqZCARtIM8ZDg6IZ2fgtVlq19FXLz3H5Udl0abNKLGKJk75B3JdSzcBROnp6GUiUYlOEfoBovBiEWvP95rCZc1zMG05WZYV1xFwG9E6Gr5VC57KkPJyMmrWBmmLZ3pal1tU93SDUt90BT9TqGKnuAH2iu+tDMDFGDlmPDP5oJUAG+CIfGDkDSckd9W5+CmPgbLL8NjxGoQn6R0b/oW+Jcyp3zUZDpjsYHau3n/mXZ5nYerP1zTtcDMjEf7aakssZ9gGK7XCEvkBAbQC9C5H7fzBVnhSnUAXXLO69JZ524LjAGgAKflNqwZyxw/QKzibtTc8MI4JXjM4C1QtPlFBfaoQbXUFg3DGqiTiFrbdE6rbpvoUN7Nl/ETr4kz8BDcn1S1R0Cqt4XrrXJYf9XehOskT7+/0Wf7LnVskR9qkrdEycGRZurUFEJPt3yOddCFsQGv65rroYVSZJD6t/JtY9Qmz2BVmXiouxJvhlTPWHxIYENxIBoo3VpjSjpVgPEZFx8MlOEeHTyR8yP+Yj17YEimIOr06f5ctWun4ZK/WE4HLjvMmFI18GDAanFFMEoq2whDH5q3g6yB91YgPFjsmsKPkBmPvVIfLtcWW5h6HuisFvprSfV180klfet48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
