travis:
  secure:
    BINSTAR_TOKEN: PhZQ010h8ZFCO3BQeUYCOdgeD+x6rfYA3NdrZywCy4B6gYlSdVDS40dx8PBcgUKSkHhLCZLA0egJmwQ97qAZvpDhOl753dk0xkzZ9BmwFiun2F9ZPCBpgYAfoqtxkfKQ3Pm/+me5ah+wE2PzC9RcygtqXMr7OZqpb5Ao78x9DnmBMk5s0yH5Knm/k36MFN4WI+L/i1Fq4fYIAVJN9kh/psx4iYpm4/NYyJWmO0PyKk6vcMOaoopKCA+Woy4OhNU7/5ZsOAIpXPo8Fs+AiPmLQcI5DSZjnLZyyFMwFl+beuG8ueHUSJkMu0qAnW01OT7QTDUU/3LSf+vWtsPgcUEMAV5l5gp67MaZHh+iT2yaxsnnuJLtSF1rUt3wq+JTWDg5x/x58otIaKFVUmsI+lgZS8/YOx3fksFyDTCFUSSqT7iBzf3xby6baVWufOq7wXm81ZEhTvhkOxPSEoipWnl2mkMEKpS8oFe9BQo3ayZacaitngYxRXurDhDWyC360QbMs0cTHVyopKJ1MDEzZlwKTu5I4teRlY49VzlpsxoGrmA4d/IEXPyPtQJzJGQCL25FXD23o2ekNFv90mhB6RBh3wA8aTD2y0+aRmpVlDL78ajU8GQQz7QFroqvushYhnTGdm9bnuN+YSPG8bIiei2nyi2EdwQPR+8fgpLg2cubaGI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
